#!/usr/bin/env python3
"""Build a fresh tutorial scaffold and the marked complete documentation modules.

Iris must already be installed in the selected compiler's package environment.
The default build is offline after dependencies are installed. --mobile-cli
opts into the real Pack/mobile setup path; --capacitor also enables packaging.
No native SDK is needed.
"""
import argparse
import importlib.util
import json
from pathlib import Path
import shutil
import subprocess
import sys
import tempfile

ROOT = Path(__file__).resolve().parents[1]
spec = importlib.util.spec_from_file_location('check_docs', ROOT / 'scripts/check-docs.py')
docs = importlib.util.module_from_spec(spec)
spec.loader.exec_module(docs)


def run(argv, cwd):
    subprocess.run([str(item) for item in argv], cwd=cwd, check=True)


def main():
    parser = argparse.ArgumentParser(description=__doc__)
    parser.add_argument('--compiler', default='idris2')
    parser.add_argument('--capacitor', type=Path)
    parser.add_argument('--mobile-cli', action='store_true',
                        help='exercise the real mobile CLI (requires Pack/Git and mobile dependencies)')
    args = parser.parse_args()
    snippets = docs.examples()
    output = ROOT / 'tests/build/docs/greeter'
    output.parent.mkdir(parents=True, exist_ok=True)
    with tempfile.TemporaryDirectory(prefix='iris-docs-') as directory:
        temporary = Path(directory)
        project = temporary / 'greeter'
        run([sys.executable, ROOT / 'tools/iris.py', 'new', 'greeter', '--project', project, '--target', 'web'], temporary)
        integration = args.mobile_cli or args.capacitor is not None
        # A placeholder is sufficient for scaffold generation and raw compilation.
        # Only the explicit integration mode obtains/uses a real library checkout.
        add_mobile = [sys.executable, ROOT / 'tools/iris.py', 'add', 'mobile',
                      '--app-id', 'com.example.greeter', '--app-name', 'Greeter']
        if args.capacitor:
            add_mobile += ['--capacitor', args.capacitor.resolve()]
        elif not integration:
            add_mobile += ['--capacitor', temporary / 'capacitor']
        run(add_mobile, project)
        for name in ['src/Greeter.idr', 'src/MainWeb.idr', 'src/MainMobile.idr']:
            if (project / name).read_text().strip() != snippets[name].strip():
                raise ValueError(f'Tutorial does not match generated scaffold: {name}')
        if integration:
            # The tutorial's git-pinned map is unchanged for this real CLI check.
            run([sys.executable, ROOT / 'tools/iris.py', 'compile'], project)
        # Raw compilation uses the selected compiler's installed Iris package.
        pack = project / 'pack.toml'
        text = pack.read_text()
        tail = text[text.index('[custom.all.greeter-web]'):]
        pack.write_text('[custom.all.iris]\ntype = "local"\npath = ' + json.dumps(str(ROOT)) + '\nipkg = "iris.ipkg"\n\n' + tail)
        for name, source in snippets.items():
            (project / name).parent.mkdir(parents=True, exist_ok=True)
            (project / name).write_text(source)
        for target in ['web', 'mobile']:
            run([args.compiler, '--cg', 'javascript', '--build', target + '.ipkg'], project)
            run(['node', '--check', project / 'build/exec' / ('greeter-' + target)], project)
        run([args.compiler, '-p', 'iris', '--check', 'RequestExample.idr'], project / 'src')
        if args.capacitor:
            run([sys.executable, ROOT / 'tools/iris.py', 'build'], project)
        # A browser preview of the same compiled mobile runner, without plugins.
        (project / 'canvas-preview.html').write_text(
            '<!doctype html><html><head><meta name="viewport" content="width=device-width,initial-scale=1">'
            '<link rel="stylesheet" href="public/canvas.css"></head><body><canvas id="iris-canvas"></canvas>'
            '<script src="build/exec/greeter-mobile"></script></body></html>\n')
        # Native outputs contain absolute ownership paths; do not copy them to a different owner.
        if output.exists():
            if not (output / '.iris-docs-fixture').is_file():
                raise ValueError(f'Refusing to replace an unowned documentation fixture: {output}')
            shutil.rmtree(output)
        shutil.copytree(project, output, ignore=shutil.ignore_patterns('.workspace'))
        (output / '.iris-docs-fixture').write_text('Generated by scripts/test-docs.py\n')
    print('Documentation tutorial compiled: ' + str(output))


if __name__ == '__main__':
    main()
